#include "../include/Report.h"
#include <iostream>

Report::Report(std::string reportID, std::string generatedBy, std::string dateRange, std::vector<Item*> items) {
    this->reportID = reportID;
    this->generatedBy = generatedBy;
    this->dateRange = dateRange;
    this->items = items;
}

void Report::generateReport() {
    std::cout << "--- System Report ---\n"
              << "Report ID: " << reportID << " | Generated By: " << generatedBy << " | Range: " << dateRange << "\n"
              << "Total Items: " << items.size() << "\n";
    for (Item* item : items) {
        std::cout << "- ";
        item->getDetails();
    }
}

void Report::countByStatus() {
    int found = 0, underReview = 0, claimed = 0, returned = 0, disputed = 0, expired = 0;
    for (Item* item : items) {
        std::string s = item->getStatus();
        if (s == "Found") found++;
        else if (s == "UnderReview") underReview++;
        else if (s == "Claimed") claimed++;
        else if (s == "Returned") returned++;
        else if (s == "Disputed") disputed++;
        
        if (item->isExpired()) expired++;
    }
    std::cout << "--- Status Counts ---\n"
              << "Found: " << found << "\n"
              << "UnderReview: " << underReview << "\n"
              << "Claimed: " << claimed << "\n"
              << "Returned: " << returned << "\n"
              << "Disputed: " << disputed << "\n"
              << "Expired: " << expired << "\n";
}

void Report::listExpired() {
    std::cout << "--- Expired Items ---\n";
    for (Item* item : items) {
        if (item->isExpired()) {
            std::cout << "- ";
            item->getDetails();
        }
    }
}

std::string Report::getReportID() { return reportID; }
std::string Report::getGeneratedBy() { return generatedBy; }
std::string Report::getDateRange() { return dateRange; }
