#include "../include/Report.h"
#include "../include/Item.h"
#include <iostream>
#include <vector>

extern std::vector<Item*> globalItems;

Report::Report(std::string reportID, std::string generatedBy, std::string dateRange) {
    this->reportID = reportID;
    this->generatedBy = generatedBy;
    this->dateRange = dateRange;
}

int Report::countByStatus(std::string status) {
    int count = 0;
    for (Item* item : globalItems) {
        if (item->getStatus() == status) {
            count++;
        }
    }
    return count;
}

void Report::generateReport() {
    std::cout << "\n=== System Report ===\n";
    std::cout << "Report ID: " << reportID << "\n";
    std::cout << "Generated By: " << generatedBy << "\n";
    std::cout << "Date Range: " << dateRange << "\n";
    std::cout << "---------------------\n";
    std::cout << "Total Items: " << globalItems.size() << "\n";
    std::cout << "Found Items: " << countByStatus("Found") << "\n";
    std::cout << "Under Review: " << countByStatus("UnderReview") << "\n";
    std::cout << "Returned Items: " << countByStatus("Returned") << "\n";
    std::cout << "---------------------\n";
    std::cout << "Item Details:\n";
    for (Item* item : globalItems) {
        std::cout << "- [" << item->getItemID() << "] " 
                  << item->getDesc() << " (Status: " << item->getStatus() << ")\n";
    }
    std::cout << "=====================\n";
}

void Report::listExpired() {
    std::cout << "\n--- Expired Items ---\n";
    bool found = false;
    for (Item* item : globalItems) {
        if (item->isExpired()) {
            std::cout << "- [" << item->getItemID() << "] " << item->getDesc() << "\n";
            found = true;
        }
    }
    if (!found) {
        std::cout << "No expired items found.\n";
    }
    std::cout << "---------------------\n";
}

std::string Report::getReportID() {
    return reportID;
}

std::string Report::getGeneratedBy() {
    return generatedBy;
}

std::string Report::getDateRange() {
    return dateRange;
}
